# Generated by Django 3.1 on 2020-12-21 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('padre', models.JSONField(blank=True, null=True)),
                ('madre', models.JSONField(blank=True, null=True)),
                ('representante', models.JSONField(blank=True, null=True)),
                ('contacto_emergencia', models.JSONField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('historia_clinica', models.CharField(blank=True, max_length=20, null=True)),
                ('trastornos_asociados', models.TextField(blank=True, null=True)),
                ('grado_dependencia', models.TextField(blank=True, null=True)),
                ('bono', models.CharField(default='Ninguno', max_length=50)),
                ('tipo_bono', models.CharField(max_length=50)),
                ('afiliacion_iess', models.CharField(max_length=10)),
                ('quintil_pobreza', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Alumno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlumnoAula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('diagnostico_clinico', models.TextField(blank=True, null=True)),
                ('numero_matricula', models.CharField(default='', max_length=155)),
                ('matricula', models.TextField(blank=True, null=True)),
                ('aporte_voluntario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tratamiento', models.TextField(blank=True, null=True)),
                ('info_faltas', models.JSONField(blank=True, null=True)),
                ('diagnostico_final', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'AlumnoAulas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('capacidad', models.PositiveSmallIntegerField()),
                ('grado', models.PositiveSmallIntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('jornada', models.CharField(default='MATUTINA', max_length=50)),
            ],
            options={
                'db_table': 'Aulas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Discapacidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Discapacidades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FuncionPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'RolesPersonal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PeriodoLectivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('nombre', models.CharField(max_length=155)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(max_length=30)),
                ('fecha_fin_clases', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('responsables', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PeriodoLectivos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('identificacion', models.CharField(max_length=30, unique=True)),
                ('tipo_identificacion', models.CharField(max_length=20)),
                ('primer_nombre', models.CharField(max_length=30)),
                ('segundo_nombre', models.CharField(max_length=30)),
                ('primer_apellido', models.CharField(max_length=30)),
                ('segundo_apellido', models.CharField(max_length=30)),
                ('pais_nacimiento', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(max_length=10)),
                ('estado_civil', models.CharField(blank=True, max_length=20, null=True)),
                ('tiene_discapacidad', models.CharField(default='NO', max_length=10)),
                ('carnet_conadis', models.CharField(default='NO REGISTRA', max_length=50)),
                ('porcentaje_discapacidad', models.PositiveSmallIntegerField(default=0)),
                ('etnia', models.CharField(blank=True, max_length=30, null=True)),
                ('tipo_sangre', models.CharField(blank=True, max_length=30, null=True)),
                ('pais_residencia', models.CharField(blank=True, max_length=150, null=True)),
                ('provincia_residencia', models.CharField(blank=True, max_length=150, null=True)),
                ('canton_residencia', models.CharField(blank=True, max_length=150, null=True)),
                ('parroquia_residencia', models.CharField(blank=True, max_length=150, null=True)),
                ('direccion_domiciliaria', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('celular_uno', models.CharField(blank=True, max_length=20, null=True)),
                ('celular_dos', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.CharField(blank=True, max_length=30, null=True)),
                ('foto', models.URLField(blank=True, null=True)),
                ('extras', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Personas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('info', models.JSONField(blank=True, null=True)),
                ('historico', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Personal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListaReproduccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('videos', models.JSONField(blank=True, null=True)),
                ('alumnos', models.JSONField(blank=True, null=True)),
                ('creador', models.JSONField(blank=True, null=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
            ],
            options={
                'db_table': 'ListaReproduccion',
                'ordering': ('titulo',),
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('descripcion_hablada', models.TextField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('docente', models.JSONField(blank=True, null=True)),
                ('estudiantes', models.JSONField(blank=True, null=True)),
                ('alumnos', models.JSONField(blank=True, null=True)),
                ('estado_envio', models.CharField(default='PENDIENTE', max_length=20)),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'db_table': 'MLN_Tareas',
                'ordering': ('-created_at',),
            },
        ),
    ]
