# Generated by Django 3.1 on 2020-12-23 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alumno',
            table='Alumnos',
        ),
    ]
