# Generated by Django 3.1 on 2020-11-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('auth_estado', models.CharField(max_length=10)),
                ('padre', models.JSONField(blank=True, null=True)),
                ('madre', models.JSONField(blank=True, null=True)),
                ('representante', models.JSONField(blank=True, null=True)),
                ('contacto_emergencia', models.JSONField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Alumno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlumnoAula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('auth_estado', models.CharField(max_length=10)),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('numero_faltas', models.SmallIntegerField()),
                ('tratamiento', models.TextField()),
                ('diagnostico', models.TextField()),
                ('diagnostico_final', models.TextField(blank=True, null=True)),
                ('aporte_voluntario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('matricula', models.TextField()),
                ('faltas', models.JSONField()),
                ('numero_matricula', models.CharField(max_length=155)),
            ],
            options={
                'db_table': 'AlumnoAula',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('auth_estado', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('capacidad', models.SmallIntegerField()),
                ('grado', models.SmallIntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('jornada', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Aula',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Discapacidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('auth_estado', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('porcentaje', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Discapacidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('auth_estado', models.CharField(max_length=10)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_titulo', models.CharField(max_length=120)),
                ('titulo', models.CharField(max_length=255)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Docente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('auth_estado', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=20)),
                ('grado', models.SmallIntegerField()),
                ('horas_presencial', models.SmallIntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('objetivo', models.TextField(blank=True, null=True)),
                ('objetivo_especifico', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Materia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notamateria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('auth_estado', models.CharField(max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('materia', models.JSONField()),
                ('notas', models.JSONField()),
            ],
            options={
                'db_table': 'NotaMateri',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Periodolectivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('auth_estado', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=155)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(max_length=30)),
                ('fecha_fin_clases', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('responsables', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PeriodoLectivo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('auth_estado', models.CharField(max_length=10)),
                ('identificacion', models.CharField(max_length=30, unique=True)),
                ('tipo_identificacion', models.CharField(max_length=20)),
                ('primer_nombre', models.CharField(max_length=30)),
                ('segundo_nombre', models.CharField(max_length=30)),
                ('primer_apellido', models.CharField(max_length=30)),
                ('segundo_apellido', models.CharField(max_length=30)),
                ('genero', models.CharField(max_length=10)),
                ('sexo', models.CharField(max_length=10)),
                ('foto', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo_sangre', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('calle_principal', models.CharField(blank=True, max_length=150, null=True)),
                ('calle_secundaria', models.CharField(blank=True, max_length=150, null=True)),
                ('lugar_referencia', models.CharField(blank=True, max_length=150, null=True)),
                ('numero_casa', models.CharField(blank=True, max_length=30, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.CharField(blank=True, max_length=30, null=True)),
                ('tiene_discapacidad', models.CharField(max_length=10)),
                ('carnet_conadis', models.CharField(max_length=50)),
                ('porcentaje_discapacidad', models.SmallIntegerField()),
                ('ocupacion', models.CharField(blank=True, max_length=120, null=True)),
                ('nivel_formacion', models.CharField(blank=True, max_length=255, null=True)),
                ('extras', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Persona',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='tarea',
            name='alumnos',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
