# Generated by Django 3.1 on 2020-11-15 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201103_0221'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaReproduccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('videos', models.JSONField(blank=True, null=True)),
                ('alumnos', models.JSONField(blank=True, null=True)),
                ('creador', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ListaReproduccion',
                'ordering': ('titulo',),
            },
        ),
        migrations.AlterModelOptions(
            name='tarea',
            options={'ordering': ('-created_at',), 'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
    ]
