# Generated by Django 3.1 on 2020-11-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201114_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='listareproduccion',
            name='auth_estado',
            field=models.CharField(default='A', max_length=10),
        ),
    ]
